### ISSUE TITLE
Unable to load skill in NeonAI

### ISSUE THREAD

**Issue by aofc** [jumper047/mycroft-mqtt-adapter#1]
Hi. Hoping to resolve this issue, I tried that skill in a Mycroft sandbox a few months ago and was looking forward to use it once I got my MarkII (need it to make it speak from another system that is already using MQTT). Now that I'm ready to use it I can't get it to load. I'm using latest stable version of NeonAI. Wondering if it could be a compatibility issue. Here are the logs. Any help? My settings.json file looks fine... with all the required settings. 
[mycroft-mqtt-adapter.log](https://github.com/jumper047/mycroft-mqtt-adapter/files/11523338/mycroft-mqtt-adapter.log)

**Comment by jumper047** [comment]
Hi, thank you for reporting! I never tried to launch my skill on Neon - I'll try to spare some time next week to reproduce that issue.  From logs you provided it's unclear what's going on - can you give me more log lines if possible. Also I'm interested in skill config -  `.config/mycroft/skills/mycroft-mqtt-adapter.jumper047/settings.json` (be careful - it contains your mqtt password, replace it before posting:))

**Comment by aofc** [comment]
[settings.json.txt](https://github.com/jumper047/mycroft-mqtt-adapter/files/11524815/settings.json.txt)
Here is my settings file, I tried the port number both with and without quotes. Had to rename the file to put it here.  I checked my logs and these are all the lines that are relevant, sorry. 
[mycroft-mqtt-adapter.log](https://github.com/jumper047/mycroft-mqtt-adapter/files/11524846/mycroft-mqtt-adapter.log)
The problem arises when I enable the skill, here you can see the log when I disable then enable the skill. pretty much the same

**Comment by aofc** [comment]
I don't really know what happened, but it's working now! Changed the names of the topics and voilà, it decided to load. So I guess it is compatible after all. :) Thank you for your time and for this skill.

**Comment by jumper047** [comment]
Awesome (though, personally I don't like bugs that disappears by themselves and will try to figure out why that happens:))!
> Thank you for your time and for this skill.

Glad it is useful for you!
